name: "Terraform Destroy"

on:
  workflow_dispatch:

env:
  TF_WORKSPACE: "pruebaIngPlataforma"
  TF_CLOUD_ORGANIZATION: "${{ secrets.TF_CLOUD_ORGANIZATION }}"
  TF_API_TOKEN: "${{ secrets.TF_API_TOKEN }}"
  AWS_ACCESS_KEY_ID: "${{ secrets.AWS_ACCESS_KEY_ID }}"
  AWS_SECRET_ACCESS_KEY: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
  AWS_REGION: "${{ secrets.AWS_REGION }}"
  CONFIG_DIRECTORY: "./Terraform/Prueba_1/EC2"


jobs:
  terraform_destroy:
    if: github.repository != 'PruebaIngPlataforma'
    name: "Terraform_destroy"
    runs-on: ubuntu-latest
    permissions: # granular permissions
      # so GitHub can check out this repo using the default github.token
      contents: read
    defaults:
      run:
        working-directory: ${{ env.CONFIG_DIRECTORY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.0
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Init
        id: init
        run: terraform init -backend-config="token=${{ secrets.TF_API_TOKEN }}" -backend-config="organization=PruebaIngPlataforma" -backend-config="workspaces=PruebaIngPlataforma" #--config="workspaces.name=PruebaIngPlataforma"
        env:
            TF_API_TOKEN: ${{ secrets.TFC_TOKEN }}
            TF_CLOUD_ORGANIZATION: "PruebaIngPlataforma"  
            TF_WORKSPACE: "PruebaIngPlataforma"
        
              
      - name: Terraform Destroy
        id: destroy
        working-directory: ${{ github.event.inputs.resource }}
        run: terraform destroy -auto-approve 
        env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
            TF_API_TOKEN: ${{ secrets.TFC_TOKEN }}
