name: "Terraform Apply New"

on:
  push:
    branches: [ "prueba_inicial_terraform_output" ]

env:
  CONFIG_DIRECTORY: "./Terraform/Prueba_1/EC2"


jobs:
  terraform_apply:
    if: github.repository != 'PruebaIngPlataforma'
    name: "Terraform_apply"
    runs-on: ubuntu-latest
    permissions: # granular permissions
      # so GitHub can check out this repo using the default github.token
      contents: read
    defaults:
      run:
        working-directory: ${{ env.CONFIG_DIRECTORY }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      - name: Configure Terraform credentials file
        run: |
          mkdir -p ~/.terraform.d
          echo '{
            "credentials": {
              "app.terraform.io": {
                "token": "'${TF_API_TOKEN}'"
              }
            }
          }' > ~/.terraform.d/credentials.tfrc.json
        env:
          TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        env:
          TF_VAR_region: ${{ secrets.AWS_REGION }}
          TF_VAR_branch: ${{ steps.extract_branch.outputs.branch }}
          TF_VAR_new_relic_account: ${{ secrets.NEW_RELIC_ACCOUNT }}
          TF_VAR_new_relic_api_key: ${{ secrets.NEW_RELIC_API_KEY }}
          TF_VAR_new_relic_region: ${{ secrets.NEW_RELIC_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: terraform plan

      - name: Terraform Apply
        env:
          TF_VAR_region: ${{ secrets.AWS_REGION }}
          TF_VAR_branch: ${{ steps.extract_branch.outputs.branch }}
          TF_VAR_new_relic_account: ${{ secrets.NEW_RELIC_ACCOUNT }}
          TF_VAR_new_relic_api_key: ${{ secrets.NEW_RELIC_API_KEY }}
          TF_VAR_new_relic_region: ${{ secrets.NEW_RELIC_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: terraform apply -auto-approve